server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://{mysql_ip}:{port}/test?useUnicode=true&characterEncoding=utf8
    username: guest
    password: guest
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  #type-aliases-package: com.jwen.addressbook.domain  # 注意：对应实体类的路径